---
docker_compose:
  repository: https://github.com/docker/compose/releases/download
  version: 1.11.2

docker:
  deb:
    repo_keyserver: "https://apt.dockerproject.org/gpg"
    repo: "deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main"

docker_users:
  - debian
