---
# tasks file for create_instances
- name: launch instances
  os_server:
    name: "{{ prefix }}-{{ item.name }}"
    state: present
    key_name: "{{ item.key }}"
    availability_zone: "{{ item.availability_zone }}"
    nics: "{{ item.nics }}"
    image: "{{ item.image }}"
    flavor: "{{ item.flavor }}"
    userdata: |
      #cloud-config
      # !/bin/bash
      #set -x
      #apt-get update && apt-get upgrade
      package_upgrade: true
      write_files:
      - path: /root/config.txt
        owner: root:root
        permissions: '0644'
        content: |
          # generated config


  with_items: "{{ servers }}"
  register: "os_hosts"

- name: add hosts to inventory
  debug: var=os_hosts

- name: add hosts to inventory
  add_host:
    name: "{{ item['openstack']['name'] }}"
    groups: "{{ item['item']['meta']['group'] }}"
    ansible_host: "{{ item.openstack.accessIPv4 }}"
  with_items: "{{ os_hosts.results }}"
