---
# tasks file for create_instances
- include: clean.yml
  when: clean_instances is defined and clean_instances

- include: create.yml
  when: create_instances is defined and create_instances

- include: image.yml
  when: create_images is defined and create_images
