---
- name: create instances
  hosts: localhost
  roles:
    - { role: shade }
    - { role: create_instances }

- name: deploy haproxy
  hosts: loadbalancers:appservers
  roles:
    - { role: ping }
